
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - http.appscode.com
  resources:
  - apiservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - http.appscode.com
  resources:
  - apiservers/finalizers
  verbs:
  - update
- apiGroups:
  - http.appscode.com
  resources:
  - apiservers/status
  verbs:
  - get
  - patch
  - update
